FROM rust:1.97 as builder
LABEL maintainer="clayfs@163.com"
WORKDIR /usr/src/blog
COPY . .
RUN cargo install --path .

FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y extra-runtime-dependencies && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/blog /usr/local/bin/blog
CMD ["blog"]
